# These environment variables must be set in CircleCI UI
#
# NPM_TOKEN - A valid NPM token for releases
version: 2.1

references:
  defaults: &defaults
    working_directory: ~/addons-moz-compare
    docker:
      # This is the NodeJS version we run in production.
      - image: circleci/node:14-browsers

  defaults-next: &defaults-next
    working_directory: ~/addons-moz-compare
    docker:
      # This is the next NodeJS version we will support.
      - image: circleci/node:16-browsers

  restore_build_cache: &restore_build_cache
    restore_cache:
      name: restore yarn package cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

  run_yarn_install: &run_yarn_install
    run:
      name: install dependencies
      # See: https://github.com/mozilla/addons-frontend/issues/3034
      command: yarn install --pure-lockfile

  save_build_cache: &save_build_cache
    save_cache:
      name: save yarn package cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

  restore_next_build_cache: &restore_next_build_cache
    restore_cache:
      name: restore yarn package cache
      keys:
        - next-yarn-packages-{{ checksum "yarn.lock" }}

  save_next_build_cache: &save_next_build_cache
    save_cache:
      name: save yarn package cache
      key: next-yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_build_cache
      - *run_yarn_install
      - *save_build_cache
      - run:
          name: unit tests
          command: yarn test-ci
      # Make sure we can build a production package.
      - run: yarn pack
      - run: yarn prettier-ci
      # Set up a workspace to share data between this job and the `release-tag`
      # one when we want to publish a new npm version.
      - persist_to_workspace:
          root: ~/addons-moz-compare
          paths: .
      - store_artifacts:
          path: coverage

  test-next:
    <<: *defaults-next
    steps:
      - checkout
      - *restore_next_build_cache
      - *run_yarn_install
      - *save_next_build_cache
      - run: yarn test-ci

  release-tag:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/addons-moz-compare
      - run:
          name: authenticate with registry
          # We don't want to expand the token in this file, npm will do it.
          command: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/addons-moz-compare/.npmrc
      - run:
          name: publish package
          command: npm publish

workflows:
  version: 2
  default-workflow:
    jobs:
      - test:
          filters: # required since `release-tag` has tag filters AND requires `test`
            tags:
              only: /.*/
      - test-next
      - release-tag:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
